// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQROdlXtz2KJa1g9-gn5d4UdGAUihTcF8',
    appId: '1:780386061070:web:14520dc2fdc8d1de3f655f',
    messagingSenderId: '780386061070',
    projectId: 'pikmin-postcard-book',
    authDomain: 'pikmin-postcard-book.firebaseapp.com',
    storageBucket: 'pikmin-postcard-book.firebasestorage.app',
    measurementId: 'G-WC2EMBMWG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2FCtv3YOeMhe2GUwVDwTIf_oNflFQA0',
    appId: '1:780386061070:android:8df259d46b7701933f655f',
    messagingSenderId: '780386061070',
    projectId: 'pikmin-postcard-book',
    storageBucket: 'pikmin-postcard-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECXT1AeGJ5MpKgQJud0LaZ8LZkhPcs9Q',
    appId: '1:780386061070:ios:310eb3ef6e3325a43f655f',
    messagingSenderId: '780386061070',
    projectId: 'pikmin-postcard-book',
    databaseURL: 'https://pikmin-postcard-book-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pikmin-postcard-book.firebasestorage.app',
    iosBundleId: 'com.admin.pikminPostcardBook',
  );

}